Remove deprecated warn kwarg for matplotlib use
The warn param has been deprecated in 3.2.1: https://matplotlib.org/3.2.1/api/prev_api_changes/api_changes_3.2.0.html#matplotlib-use

On the most recent matplotlib, this is failing for me with 

TypeError: use() got an unexpected keyword argument 'warn'