hdfs: Allow hdfs read/write for files
Now the following will work:

If hdfs3 is not installed, Throws:
  ImportError: The hdfs3 library is required to handle hdfs files

If hdfs3 is installed but libhdfs3 is not installed, Throws:
  ImportError: Can not find the shared library: libhdfs3.so

If hdfs3 is installed it works for the code:
  pd.read_csv("hdfs://localhost:9000/tmp/a.csv")

If hdfs3 is installed and HADOOP_CONF_DIR is set, it works for the code:
  HADOOP_CONF_DIR=/usr/local/Cellar/hadoop/2.7.0/libexec/etc/hadoop/
  pd.read_csv("hdfs:///tmp/a.csv")