Fix docstring timestamps#59458 (#59533)
* Fix docstrings for pandas.Period.year SA01

* Fix docstrings for pandas.Period.year SA01 Validate Docstrings err

* Fix docstrings for pandas.Period.year SA01 Validate Docstrings err

* Fix docstrings for pandas.timestamps SA01 PR01

* This reverts commit f52c61080a331597197711465742ace1bdfcd1dd.

* Revert "Removed dateparseerror example from period.year"

This reverts commit cdf36b2faa6c95848d6210c801ee287f0b7084fd.

* fixing merge conflict

* fix pre-commit.ci err

* fix pre-commit.ci err

* fix Docstring validation err

* fix Docstring validation err

* fix Docstring validation err

* fix timestamp Docstring validation err

* pandas/plotting/_matplotlib/core.py:549: error: Unused "type: ignore" comment [unused-ignore]

---------

Co-authored-by: Matthew Roeschke <10647082+mroeschke@users.noreply.github.com>