Yet again improve typo in test_groupby.py
##[error]pandas/tests/groupby/test_groupby.py:2062:         <- trailing whitespaces found
##[error]./pandas/tests/groupby/test_groupby.py:15:1:F811:redefinition of unused 'Series' from line 11
##[error]ERROR: /home/runner/work/pandas/pandas/pandas/tests/groupby/test_groupby.py Imports are incorrectly sorted.